#!/usr/bin/env python3
"""
Download S&P 500 + Nasdaq 100 tickers and save to config/universe-sp500.txt.
Used by discovery.py --universe sp500.

Usage:
    python scripts/update-universe.py

Re-run monthly to catch index changes.
"""

import csv
import io
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT  = ROOT / "config" / "universe-sp500.txt"
UA   = "Mozilla/5.0"


def fetch_csv(url, symbol_col):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    data = urllib.request.urlopen(req, timeout=15).read().decode("utf-8")
    reader = csv.DictReader(io.StringIO(data))
    return [row[symbol_col].replace(".", "-") for row in reader if row.get(symbol_col)]


def main():
    tickers = set()

    print("Fetching S&P 500...", file=sys.stderr)
    try:
        sp = fetch_csv(
            "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv",
            "Symbol",
        )
        tickers.update(sp)
        print(f"  S&P 500: {len(sp)} tickers", file=sys.stderr)
    except Exception as e:
        print(f"  [warn] S&P 500 failed: {e}", file=sys.stderr)

    # Nasdaq removed — S&P 500 pure list is sufficient for quality screening
    # and keeps the universe small enough to scan in reasonable time

    if not tickers:
        print("ERROR: no tickers fetched", file=sys.stderr)
        sys.exit(1)

    combined = sorted(tickers)
    lines = [
        "# S&P 500 + Nasdaq universe",
        "# Auto-generated by scripts/update-universe.py",
        "# Re-run monthly to catch index changes",
        "",
    ] + combined

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Saved {len(combined)} tickers -> {OUT.name}", file=sys.stderr)
    print(f"Done: {len(combined)} tickers")


if __name__ == "__main__":
    main()
