#!/usr/bin/env python3
"""
YouTube Transcript Fetcher — downloads subtitles and saves to vault/00_inbox/.

Usage:
  python scripts/youtube-transcript.py <YouTube URL>
  python scripts/youtube-transcript.py https://youtu.be/xxxxx

Output:
  vault/00_inbox/<title>-transcript-YYYY-MM-DD.md
  Prints transcript path — paste to Claude for summarization

Requires: pip install youtube-transcript-api
Optional:  pip install yt-dlp  (fallback for auto-generated captions)

Truncates transcript at 8000 chars to keep Claude token cost low.
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT       = Path(__file__).resolve().parent.parent
INBOX_DIR  = ROOT / "vault/00_inbox"
MAX_CHARS  = 8000


def _slug(text: str) -> str:
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_]+", "-", text).strip("-")[:60]


def fetch_via_api(video_id: str) -> tuple[str, list]:
    from youtube_transcript_api import YouTubeTranscriptApi
    transcript = YouTubeTranscriptApi.get_transcript(video_id, languages=["en", "th"])
    return "youtube_transcript_api", transcript


def fetch_via_ytdlp(url: str) -> tuple[str, list]:
    import subprocess
    import json
    import tempfile
    import os

    with tempfile.TemporaryDirectory() as tmp:
        result = subprocess.run(
            ["yt-dlp", "--write-auto-sub", "--skip-download",
             "--sub-format", "json3", "--output", f"{tmp}/%(title)s",
             "--print", "title", url],
            capture_output=True, text=True, timeout=60,
        )
        title = result.stdout.strip().split("\n")[0]
        sub_files = list(Path(tmp).glob("*.json3"))
        if not sub_files:
            raise FileNotFoundError("No subtitle file generated by yt-dlp")
        data = json.loads(sub_files[0].read_text(encoding="utf-8"))
        events = data.get("events", [])
        segments = []
        for ev in events:
            segs = ev.get("segs", [])
            text = "".join(s.get("utf8", "") for s in segs).strip()
            if text:
                segments.append({"text": text, "start": ev.get("tStartMs", 0) / 1000})
    return title, segments


def extract_video_id(url: str) -> str:
    patterns = [
        r"youtu\.be/([A-Za-z0-9_-]{11})",
        r"youtube\.com/watch\?.*v=([A-Za-z0-9_-]{11})",
        r"youtube\.com/shorts/([A-Za-z0-9_-]{11})",
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            return m.group(1)
    return ""


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python scripts/youtube-transcript.py <YouTube URL>")
        sys.exit(1)

    url = sys.argv[1]
    video_id = extract_video_id(url)
    if not video_id:
        print(f"[ERROR] Cannot parse video ID from: {url}")
        sys.exit(1)

    # Try youtube_transcript_api first, then yt-dlp
    title = video_id
    segments = []
    method = ""

    try:
        method, segments = fetch_via_api(video_id)
        title = video_id
    except Exception as e1:
        print(f"  [youtube_transcript_api] failed: {e1}")
        try:
            title, segments = fetch_via_ytdlp(url)
            method = "yt-dlp"
        except Exception as e2:
            print(f"  [yt-dlp] failed: {e2}")
            print("[ERROR] Both methods failed — install: pip install youtube-transcript-api")
            sys.exit(1)

    # Build plain text from segments
    if isinstance(segments, list) and segments and isinstance(segments[0], dict):
        if "text" in segments[0]:
            full_text = " ".join(s["text"] for s in segments)
        else:
            full_text = str(segments)
    else:
        full_text = str(segments)

    # Truncate
    truncated = len(full_text) > MAX_CHARS
    text_out  = full_text[:MAX_CHARS]
    if truncated:
        text_out += f"\n\n[... truncated at {MAX_CHARS} chars — full transcript: {len(full_text)} chars]"

    # Save to vault
    INBOX_DIR.mkdir(parents=True, exist_ok=True)
    today    = date.today().isoformat()
    filename = f"{_slug(title)}-transcript-{today}.md"
    outpath  = INBOX_DIR / filename

    content = f"""---
source: youtube
url: {url}
video_id: {video_id}
fetched: {today}
method: {method}
chars: {len(full_text)}
truncated: {truncated}
---

# Transcript: {title}

*Source: {url}*
*Fetched via {method} on {today}*
{"*⚠️ Truncated at " + str(MAX_CHARS) + " chars — full: " + str(len(full_text)) + " chars*" if truncated else ""}

---

{text_out}

---

## Summarize

Paste this file to Claude and ask:
> "สรุป transcript นี้เป็น bullet points ภาษาไทย — key takeaways 5 ข้อ"
"""

    outpath.write_text(content, encoding="utf-8")
    print(f"Saved: {outpath.relative_to(ROOT)}")
    print(f"Size:  {len(full_text):,} chars {'(truncated)' if truncated else ''}")
    print(f"Next:  paste to Claude → ask to summarize")


if __name__ == "__main__":
    main()
